# Generated by Django 5.0.6 on 2024-06-03 23:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prvnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=254)),
                ('humidity', models.FloatField()),
                ('precipitat', models.FloatField()),
                ('elevation_field', models.FloatField()),
                ('temperatur', models.FloatField()),
                ('population', models.FloatField()),
                ('website', models.CharField(max_length=50)),
                ('نام_ف', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
