# Generated by Django 5.0.6 on 2024-07-04 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0002_prvnc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participants', models.IntegerField()),
                ('CourseFile', models.FileField(upload_to='.')),
                ('CourseImg', models.FileField(upload_to='.')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.IntegerField()),
                ('StudentName', models.CharField(max_length=50)),
                ('StudentLastName', models.CharField(max_length=50)),
                ('StudentBirthday', models.DateField()),
                ('StudentCourses', models.CharField(max_length=50)),
                ('StudentScorses', models.FloatField()),
                ('Datejoined', models.DateField()),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rater_name', models.CharField(max_length=255)),
                ('rater_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
