# Generated by Django 5.0.6 on 2024-07-04 14:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0003_course_student_userrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('provincnam', models.CharField(max_length=20)),
                ('cityname', models.CharField(max_length=25)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
